apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    app: hello-world
  template:
    metadata:
      name: hello-world
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: sadlil/hello-world:2.0
        ports:
        - containerPort: 8080
