apiVersion: v1
kind: Pod
metadata:
  name: netter
spec:
  containers:
  - name: netter
    image: sadlil/netter:1.0
    readinessProbe:
      exec:
        command:
          - cat
          - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5